// Student Corner — Branch & Subject Data
const SC_BRANCHES = {
  '1st Year': [
    { label:'CSE', icon:'💻', sub:'Computer Science' },
    { label:'IT',  icon:'🌐', sub:'Information Technology' },
    { label:'ECE', icon:'📡', sub:'Electronics & Comm.' },
    { label:'EEE', icon:'⚡', sub:'Electrical & Electronics' },
    { label:'ME',  icon:'⚙️', sub:'Mechanical Engg.' },
    { label:'CE',  icon:'🏗️', sub:'Civil Engineering' },
  ],
  '2nd Year': [
    { label:'CSE', icon:'💻', sub:'Computer Science' },
    { label:'IT',  icon:'🌐', sub:'Information Technology' },
    { label:'ECE', icon:'📡', sub:'Electronics & Comm.' },
    { label:'EEE', icon:'⚡', sub:'Electrical & Electronics' },
    { label:'ME',  icon:'⚙️', sub:'Mechanical Engg.' },
    { label:'CE',  icon:'🏗️', sub:'Civil Engineering' },
  ],
  '3rd Year': [
    { label:'CSE', icon:'💻', sub:'Computer Science' },
    { label:'IT',  icon:'🌐', sub:'Information Technology' },
    { label:'ECE', icon:'📡', sub:'Electronics & Comm.' },
    { label:'EEE', icon:'⚡', sub:'Electrical & Electronics' },
    { label:'ME',  icon:'⚙️', sub:'Mechanical Engg.' },
    { label:'CE',  icon:'🏗️', sub:'Civil Engineering' },
  ],
  '4th Year': [
    { label:'CSE', icon:'💻', sub:'Computer Science' },
    { label:'IT',  icon:'🌐', sub:'Information Technology' },
    { label:'ECE', icon:'📡', sub:'Electronics & Comm.' },
    { label:'EEE', icon:'⚡', sub:'Electrical & Electronics' },
    { label:'ME',  icon:'⚙️', sub:'Mechanical Engg.' },
    { label:'CE',  icon:'🏗️', sub:'Civil Engineering' },
  ]
};

const SC_SUBJECTS = {
  '1st Year_CSE': [
    { label:'Engineering Mathematics I', icon:'📐' },
    { label:'Programming in C', icon:'💾' },
    { label:'Engineering Physics', icon:'🔬' },
    { label:'Engineering Chemistry', icon:'🧪' },
    { label:'Basic Electronics', icon:'🔌' },
    { label:'English Communication', icon:'📝' },
  ],
  '1st Year_IT': [
    { label:'Engineering Mathematics I', icon:'📐' },
    { label:'Programming in C', icon:'💾' },
    { label:'Engineering Physics', icon:'🔬' },
    { label:'Engineering Chemistry', icon:'🧪' },
    { label:'Basic Electronics', icon:'🔌' },
    { label:'English Communication', icon:'📝' },
  ],
  '1st Year_ECE': [
    { label:'Engineering Mathematics I', icon:'📐' },
    { label:'Engineering Physics', icon:'🔬' },
    { label:'Engineering Chemistry', icon:'🧪' },
    { label:'Basic Electrical Engineering', icon:'⚡' },
    { label:'Programming in C', icon:'💾' },
    { label:'English Communication', icon:'📝' },
  ],
  '1st Year_EEE': [
    { label:'Engineering Mathematics I', icon:'📐' },
    { label:'Engineering Physics', icon:'🔬' },
    { label:'Engineering Chemistry', icon:'🧪' },
    { label:'Basic Electrical Engineering', icon:'⚡' },
    { label:'Programming in C', icon:'💾' },
    { label:'English Communication', icon:'📝' },
  ],
  '1st Year_ME': [
    { label:'Engineering Mathematics I', icon:'📐' },
    { label:'Engineering Physics', icon:'🔬' },
    { label:'Engineering Chemistry', icon:'🧪' },
    { label:'Engineering Drawing', icon:'📏' },
    { label:'Workshop Practice', icon:'🔧' },
    { label:'English Communication', icon:'📝' },
  ],
  '1st Year_CE': [
    { label:'Engineering Mathematics I', icon:'📐' },
    { label:'Engineering Physics', icon:'🔬' },
    { label:'Engineering Chemistry', icon:'🧪' },
    { label:'Engineering Drawing', icon:'📏' },
    { label:'Basic Civil Engineering', icon:'🏗️' },
    { label:'English Communication', icon:'📝' },
  ],
  '2nd Year_CSE': [
    { label:'Data Structures', icon:'🌳' },
    { label:'Object Oriented Programming', icon:'☕' },
    { label:'Digital Logic Design', icon:'🔢' },
    { label:'Discrete Mathematics', icon:'📐' },
    { label:'Computer Organization', icon:'🖥️' },
    { label:'Engineering Mathematics II', icon:'➕' },
  ],
  '2nd Year_IT': [
    { label:'Data Structures', icon:'🌳' },
    { label:'Object Oriented Programming', icon:'☕' },
    { label:'Digital Logic Design', icon:'🔢' },
    { label:'Database Management Systems', icon:'🗄️' },
    { label:'Computer Networks Basics', icon:'🌐' },
    { label:'Engineering Mathematics II', icon:'➕' },
  ],
  '2nd Year_ECE': [
    { label:'Network Analysis', icon:'📡' },
    { label:'Electronic Devices & Circuits', icon:'🔌' },
    { label:'Signals & Systems', icon:'📈' },
    { label:'Engineering Mathematics II', icon:'➕' },
    { label:'Digital Electronics', icon:'🔢' },
    { label:'Electromagnetic Theory', icon:'🧲' },
  ],
  '2nd Year_EEE': [
    { label:'Network Analysis', icon:'📡' },
    { label:'Electronic Devices & Circuits', icon:'🔌' },
    { label:'Electrical Machines I', icon:'⚙️' },
    { label:'Engineering Mathematics II', icon:'➕' },
    { label:'Electromagnetic Fields', icon:'🧲' },
    { label:'Signals & Systems', icon:'📈' },
  ],
  '2nd Year_ME': [
    { label:'Engineering Mechanics', icon:'⚙️' },
    { label:'Thermodynamics', icon:'🌡️' },
    { label:'Strength of Materials', icon:'🔩' },
    { label:'Manufacturing Technology I', icon:'🏭' },
    { label:'Engineering Mathematics II', icon:'➕' },
    { label:'Fluid Mechanics', icon:'💧' },
  ],
  '2nd Year_CE': [
    { label:'Structural Analysis I', icon:'🏛️' },
    { label:'Fluid Mechanics', icon:'💧' },
    { label:'Surveying', icon:'📏' },
    { label:'Engineering Mathematics II', icon:'➕' },
    { label:'Concrete Technology', icon:'🧱' },
    { label:'Engineering Geology', icon:'🪨' },
  ],
  '3rd Year_CSE': [
    { label:'Operating Systems', icon:'🖥️' },
    { label:'Database Management Systems', icon:'🗄️' },
    { label:'Computer Networks', icon:'🌐' },
    { label:'Design & Analysis of Algorithms', icon:'📊' },
    { label:'Software Engineering', icon:'🛠️' },
    { label:'Theory of Computation', icon:'🔣' },
  ],
  '3rd Year_IT': [
    { label:'Operating Systems', icon:'🖥️' },
    { label:'Database Management Systems', icon:'🗄️' },
    { label:'Computer Networks', icon:'🌐' },
    { label:'Web Technologies', icon:'🌍' },
    { label:'Software Engineering', icon:'🛠️' },
    { label:'Design & Analysis of Algorithms', icon:'📊' },
  ],
  '3rd Year_ECE': [
    { label:'Analog Communication', icon:'📻' },
    { label:'Digital Communication', icon:'📡' },
    { label:'Microprocessors & Microcontrollers', icon:'🔧' },
    { label:'VLSI Design', icon:'🔌' },
    { label:'Control Systems', icon:'🎛️' },
    { label:'Digital Signal Processing', icon:'📈' },
  ],
  '3rd Year_EEE': [
    { label:'Power Systems I', icon:'⚡' },
    { label:'Electrical Machines II', icon:'⚙️' },
    { label:'Control Systems', icon:'🎛️' },
    { label:'Power Electronics', icon:'🔌' },
    { label:'Microprocessors', icon:'🔧' },
    { label:'Digital Signal Processing', icon:'📈' },
  ],
  '3rd Year_ME': [
    { label:'Heat Transfer', icon:'🌡️' },
    { label:'Machine Design', icon:'⚙️' },
    { label:'Kinematics of Machinery', icon:'🔩' },
    { label:'Manufacturing Technology II', icon:'🏭' },
    { label:'Metrology & Measurements', icon:'📏' },
  